### PR TITLE
Pirot1 patch 1

### PR DESCRIPTION
**Pull request by Pirot1**

### CODE REVIEW

**Comment by Pirot1** [comment]
Create boilerplate

**Comment by SVilgelm** [comment]
for the future, please do not urge the PRs without my review

**Comment by SVilgelm** [comment]
firs, the PR's body should have a summary of all commits, so what is this PR about?
and in your case, the body should contain a link to the task in the project.
BTW, the project is invisible, check the settings of the project and make it public

**Comment by SVilgelm** [comment]
Please revert this PR and create again, I have several comments

**Pull request merged**
